### ISSUE TITLE
Easier Editing?

### ISSUE THREAD

**Issue by MDFL64** [sirsavary/modmountain-issues#24]
I feel like I'm filing taxes filling out the addon submission form. Maybe split it into multiple parts, or make a smaller intial submission form and make other stuff editable via the addon's page/preview page?

**Comment by sirsavary** [comment]
The edit flow isn't nearly as good as it could be. I'm thinking of redoing it so it's more like editing your addon's store page in-place. That way you can instantly see the difference.
