### ISSUE TITLE
Images don't display before an addon has been approved/published.

### ISSUE THREAD

**Issue by MDFL64** [sirsavary/modmountain-issues#25]
The server appears to respond with 403/Forbidden for each image.

**Comment by sirsavary** [comment]
Have you tried hitting the "preview" button on that view addon page?

**Comment by MDFL64** [comment]
Yeah, that's where it happens.

**Comment by sirsavary** [comment]
Very strange. Taking a look at the code now to see why this might be.

**Comment by sirsavary** [comment]
Resolved, thanks for the report!
